### ISSUE TITLE
How Do I Access a DCS Redis Instance Through Redis Desktop Manager?

### ISSUE THREAD

**Issue by uli-max** [opentelekomcloud-docs/distributed-cache-service#33]
Issue on page:        https://github.com/opentelekomcloud-docs/distributed-cache-service/blob/main/umn/source/faqs/client_and_network_connection/how_do_i_access_a_dcs_redis_instance_through_redis_desktop_manager.rst

Please replace the screenshot.

 myrediscache.redis.cache.windows.net
 
 A292593@T000d5da76 ~ % nslookup myrediscache.redis.cache.windows.net
Server:		192.168.178.1
Address:	192.168.178.1#53

Non-authoritative answer:
myrediscache.redis.cache.windows.net	canonical name = eus2-52762-1804327128.eastus2.cloudapp.azure.com.
Name:	eus2-52762-1804327128.eastus2.cloudapp.azure.com
Address: 20.122.118.200

The screenshots points to Azure, not to Open Telekom Cloud or neutral service

**Comment by robert1x2** [comment]
Its not fixed yet, can would check again please?

**Comment by amuetzelgit** [comment]
The issue was fixed with https://github.com/opentelekomcloud-docs/distributed-cache-service/pull/38

![image](https://github.com/opentelekomcloud-docs/distributed-cache-service/assets/122888151/e8c23130-e240-403c-bfd5-ca4b9a13fb6a)

**Comment by amuetzelgit** [comment]
The issue was fixed with https://github.com/opentelekomcloud-docs/distributed-cache-service/pull/38
